# This is a an example of comment in python
# We use comments to document our code and leave breadcrumbs for ourselves

# At the top of the file we declare with "packages" we want to use.
# You can think of a package as some code someone else has already written that we can use so we don't have to re-write that code.
# In this case we are using twilio package that was created by company twilio.
# Twilio company has done a bunch of work to makes it really easy to send SMS messages programatically.
from twilio.rest import Client

# At the point we declare a 'variable' called account_id
# account_id is a string type
account_id = "ACab791159e3f6723900e296c3f6ff4f7d"

# We declare a password variable (string)
# Gets generated by Twilio so that we can use their 'API'

# Ask Fernando for this
password = ""

# Here we are starting up our 'Client' program with our account_id and password
# Our Client Program requires us to
client = Client(account_id, password)

# In python world Client is called a Class
# What are Classes?

fernando_phone_number = "+13105036833"

# Here we introduce the List type.
# Here we declare a list variable with my phone number
phone_numbers_i_want_to_message = [fernando_phone_number, "+13105036833"]

# Declare a boolean variable if i have received a message
# Once i send myself a message i will set this to True
has_fernando_been_messaged = False

# Here we introduce for loops
for phone_number in phone_numbers_i_want_to_message:
    print("I'm inside the for loop.")
    print(phone_number)

    # If we haven't messaged Fernando already message him
    if has_fernando_been_messaged is False:
        print("Fernando has not been messaged")
        print("Sending him a message!")
        message = client.messages.create(to=phone_number, from_="+13104219830", body="The Tap Program is great!")

        # Set the variable has_fernando_been_messaged to True so that he stops getting messaged.
        has_fernando_been_messaged = True
    else:
        # Do thing
        continue


# Open terminal and run
# python send_sms.py

# Some things to try
# Update the password to be incorrect and run the program

# Remove the password variable from Client class and see what error message looks like
# Google the error that comes up


# Add your number to the list of phone numbers and run the program.




# Bonus: Talk about how Tradesy uses twilio API's and give other examples of API's we use...