# At the top of the file we declare what "packages" we want to use.
# You can think of a package as some code someone else has already written that we can use so we don't have to re-write that code.
# In this case we are using twilio package that was created by company twilio.
# Twilio company has done a bunch of work to makes it really easy to send SMS messages programatically.
# The twilio package lets us interact with their API (Application Programming Interface) as long as we have the right credentials
from twilio.rest import Client


# At the point we declare a 'variable' called  twilio_account_id
twilio_account_id = "Our account information"

# What is a variable?
# The purpose variable is to reference something
# Variables are declare so that they can be used and reused thru out your program
# Similar to how you would name a photo of yourself fernando.jpg so you can easily find it or
# so you know what it is if you run into it. You want to give things
# good names so that they are descriptive of what it actually is
also_account_id = ''

# We declare a password variable (string)
# Gets generated by Twilio so that we can use their 'API'
# Ask Fernando for this
password = ""


# Here we are instantiating our 'Client' class by passing it in our variables we declared above twilio_account_id and password
fernando_client = Client(twilio_account_id, password)
#caroline_client = Client(account_id, password)

# So the first thing you need to know about Classes is the difference between a class and an instance of a class.
# A class is like a blueprint, it tells you about some thing you want to make. An instance is the thing that gets made.
# So for example Client is blueprint of code that will interact with twilio api
# We could for example create two clients one for me and other for caroline


# Example
# account_id_for_caroline_twilio = "12345678ee"
# password_for_caroline = "password1"
# caroline_client = Client(account_id_for_caroline_twilio, password_for_caroline)
# With both of these Clients we can send sms messages but one client will snd using fernando's twilio account
# the Other with Caroline account for example


# Declaring another variable
fernando_phone_number = "+13105036833"

# Here we introduce the List type.
# List are
# Here we declare a list of phone numbers i want to send an sms messag too
phone_numbers_i_want_to_message = [fernando_phone_number, "+13105036833"]

# What is a list ?
# A list is collection of ordered things that can be updated
# Lists are things within two square brackets []. More then one will be separated by a comma


has_fernando_been_messaged = False
# Declare a boolean variable


# Here we introduce for loops
for phone_number in phone_numbers_i_want_to_message:
    print("I'm inside the for loop.")
    print(phone_number)

    # If we haven't messaged Fernando already message him
    if has_fernando_been_messaged is False:
        print("Fernando has not been messaged")
        print("Sending him a message!")
        message = fernando_client.messages.create(to=phone_number, from_="+13104219830", body="The Tap Program is great!")

        # Set the variable has_fernando_been_messaged to True so that he stops getting messaged.
        has_fernando_been_messaged = True
    else:
        # Do thing
        continue


# Open terminal and run
# python send_sms.py

# Some things to try
# Update the password to be incorrect and run the program

# Remove the password variable from Client class and see what error message looks like
# Google the error that comes up


# Add your number to the list of phone numbers and run the program.


# Bonus: Talk about how Tradesy uses twilio API's and give other examples of API's we use...